metadata:
  name: "Jane Doe"
  title: "Senior Cloud Architect"
  location: "Austin, TX"
  contact:
    email: "jane.doe@example.com"
    phone: "555-123-4567"
    linkedin: "linkedin.com/in/janedoe"
    github: "github.com/janedoe"

position:
  title: "Cloud Solutions Architect"
  keywords:
    - "Cloud Architecture"
    - "DevOps"
    - "Site Reliability Engineering"
summary: |
  Senior Cloud Architect with extensive experience in designing and implementing 
  scalable cloud solutions. Passionate about creating efficient, cost-effective 
  infrastructure that enables business agility. Skilled at translating technical 
  concepts for non-technical stakeholders and building consensus across teams.
  Focused on mentoring junior engineers and promoting best practices across 
  the organization.

skills:
  Leadership:
    - "Enterprise Architecture"
    - "Team Leadership"
    - "Strategic Planning"
    - "Project Management"
    - "Business-Technical Alignment"
    - "Mentoring"
  Technical:
    - "Cloud Platforms (AWS, Azure, GCP)"
    - "Infrastructure as Code (Terraform, CloudFormation)"
    - "Containerization (Docker, Kubernetes)"
    - "CI/CD Pipelines (Jenkins, GitHub Actions)"
    - "Monitoring and Observability"
    - "Serverless Architecture"
    - "Microservices Design"
    - "API Design and Implementation"

experience:
  - company: "Tech Solutions Inc."
    title: "Senior Cloud Architect"
    period: "January 2020 – Present"
    location: "Austin, TX"
    description: |
      Lead cloud architecture initiatives and establish best practices for 
      enterprise-wide cloud adoption. Design and implement scalable, secure 
      infrastructure solutions while mentoring junior team members.
    highlights:
      - "Led the migration of 50+ applications to cloud-native architecture, reducing infrastructure costs by 35% and improving scalability."
      - "Established a Cloud Center of Excellence that improved deployment efficiency by 60% and reduced security incidents by 40%."
  - company: "Tech Solutions Inc."
    title: "Cloud Engineer"
    period: "March 2017 - December 2019"
    location: "Austin, TX"
    description: |
      Designed and implemented cloud infrastructure for critical business applications. 
      Automated deployment processes and improved system reliability.
    highlights:
      - "Implemented infrastructure as code practices using Terraform, reducing provisioning time from days to minutes."
      - "Built a self-service platform for developers that increased deployment frequency by 300% while maintaining security compliance."
  - company: "Digital Innovations LLC"
    title: "Systems Engineer"
    period: "June 2014 – February 2017"
    location: "Denver, CO"
    description: |
      Managed on-premises infrastructure and supported the initial cloud migration efforts.
      Collaborated with development teams to improve system performance and reliability.
    highlights:
      - "Orchestrated the company's first cloud migration project, moving critical systems to AWS with zero downtime."

education:
  - degree: "M.S. Computer Science"
    institution: "University of Texas at Austin"
    period: "2012 - 2014"
  - certification: "AWS Certified Solutions Architect - Professional"
    period: "2020"
  - certification: "Google Cloud Professional Cloud Architect"
    period: "2021"

publications:
  - title: "Building Resilient Cloud Infrastructure"
    venue: "Cloud Computing Conference 2022"
  - title: "Best Practices for Multi-Cloud Deployments"
    venue: "DevOps Summit 2021"
